### ISSUE TITLE
dns service error

### ISSUE THREAD

**Issue by welteki** [holgerimbery/docker_homekit2mqtt#2]
The container exits with `dns service error` when started with the command described in the README.

```
/usr/lib/node_modules/homekit2mqtt/node_modules/mdns/lib/advertisement.js:56
  dns_sd.DNSServiceRegister(self.serviceRef, flags, ifaceIdx, name,
         ^

Error: dns service error: unknown
    at new Advertisement (/usr/lib/node_modules/homekit2mqtt/node_modules/mdns/lib/advertisement.js:56:10)
    at Object.create [as createAdvertisement] (/usr/lib/node_modules/homekit2mqtt/node_modules/mdns/lib/advertisement.js:64:10)
    at Advertiser.startAdvertising (/usr/lib/node_modules/homekit2mqtt/node_modules/hap-nodejs/lib/Advertiser.js:47:30)
    at Bridge.Accessory._onListening (/usr/lib/node_modules/homekit2mqtt/node_modules/hap-nodejs/lib/Accessory.js:655:20)
    at emitOne (events.js:121:20)
    at HAPServer.emit (events.js:211:7)
    at HAPServer._onListening (/usr/lib/node_modules/homekit2mqtt/node_modules/hap-nodejs/lib/HAPServer.js:190:8)
    at emitOne (events.js:116:13)
    at EventedHTTPServer.emit (events.js:211:7)
    at EventedHTTPServer.<anonymous> (/usr/lib/node_modules/homekit2mqtt/node_modules/hap-nodejs/lib/util/eventedhttp.js:65:10)
```

**Comment by welteki** [comment]
The container is not running /root/entrypoint.sh  because the command  option passed to `docker run` overrides it. Running the container with e.g `/root/entrypoint.sh homekit2mqtt -u mqtt://user:password@ip-address` as command option works fine.

**Comment by holgerimbery** [comment]
Hi,
you are right - CMD will be overridden when running the container with alternative arguments.
This is a default docker feature. The readme file is still an old version, I will corrected README and tweak the Dockerfile to eliminate this misbehavior.

Thanks for pointing me to that issue!

**Comment by holgerimbery** [comment]
#792111a
